# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build gh-pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: npm ci
    - name: build
      run: npm run docs:build
    - name: Push to gh-pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        jekyll: false 
        target_branch: gh-pages
        build_dir: .vuepress/dist
      env:
        GITHUB_TOKEN: ${{ github.token }}
